default:
  branding: false
  elementpath: false
  insert_toolbar: quickimage quicktable
  toolbar: bold italic | alignleft aligncenter alignright alignjustify | fontsizeselect
  menu: 
    file: false